# Generated by Django 2.1.1 on 2018-12-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0006_auto_20181216_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evt-owner+', to='matchings.Member')),
                ('participants', models.ManyToManyField(blank=True, related_name='_event_participants_+', to='matchings.Member')),
            ],
        ),
    ]
