# Generated by Django 2.1.1 on 2018-12-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0009_auto_20181216_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
