# Generated by Django 2.1.1 on 2018-12-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0010_auto_20181216_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
